In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
df = pd.read_csv('data/modely_03_testy_pozitivnich_2020-11-02-23-45-36.csv', delimiter=';', encoding='iso-8859-1')
df2 = pd.read_csv('data/modely_01_okresni_statistika_2020-11-02-23-45-32.csv', delimiter=';', encoding='iso-8859-1')
df

,datum_vysledku,okres,orp,pohlavi,vek_kat,pocet_pozitivni_primarni,pocet_testu_u_pozitivnich,pocet_opakovanych
0,2020-01-31,CZ0100,Praha,M,20-64,NaN,2.0,NaN
1,2020-03-03,CZ0411,Cheb,Z,20-64,NaN,1.0,NaN
2,2020-03-03,CZ0421,Dìèín,Z,20-64,1.0,NaN,NaN
3,2020-03-03,CZ0642,Brno,M,20-64,NaN,1.0,NaN
4,2020-03-04,CZ0206,Mìlník,Z,0-19,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...
96451,2020-11-02,CZ0804,Kopøivnice,Z,65+,24.0,50.0,26.0
96452,2020-11-02,CZ0804,Nový Jièín,M,20-64,14.0,28.0,14.0
96453,2020-11-02,CZ0805,Opava,Z,20-64,41.0,88.0,47.0
96454,2020-11-02,CZ0806,Ostrava,M,65+,30.0,67.0,37.0
96455,2020-11-02,CZ099Y,NaN,Z,20-64,4.0,8.0,4.0

In [58]:
df2

,datum,okres,orp,pohlavi,vek_kat,pocet_pozitivni,pocet_vyleceni,pocet_zemreli,pocet_umrti_hospitalizace,pocet_umrti_komplikovany
0,2020-03-24,CZ0802,8006,M,20-64,3.0,NaN,1.0,1.0,1.0
1,2020-03-28,CZ0100,0,Z,65+,4.0,1.0,2.0,1.0,1.0
2,2020-03-28,CZ0712,7112,M,65+,NaN,NaN,1.0,1.0,1.0
3,2020-04-04,CZ0644,6411,M,65+,NaN,NaN,1.0,1.0,0.0
4,2020-04-05,CZ0644,6404,M,65+,2.0,NaN,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
72517,2020-11-02,CZ0803,8004,Z,20-64,8.0,NaN,NaN,NaN,NaN
72518,2020-11-02,CZ0804,8016,M,20-64,2.0,NaN,NaN,NaN,NaN
72519,2020-11-02,CZ0805,8009,M,0-19,3.0,NaN,NaN,NaN,NaN
72520,2020-11-02,CZ0806,8019,M,0-19,11.0,NaN,NaN,NaN,NaN
72521,2020-11-02,CZ099Y,9999,M,20-64,10.0,NaN,NaN,NaN,NaN

In [59]:
grouped = df.groupby('vek_kat')
grouped.sum()

,pocet_pozitivni_primarni,pocet_testu_u_pozitivnich,pocet_opakovanych
vek_kat,,,
0-19,45252.0,107381.0,50967.0
20-64,255832.0,656379.0,345595.0
65+,49711.0,137736.0,65206.0

In [60]:
del df2['orp']
del df2['pocet_vyleceni']
del df2['pocet_umrti_hospitalizace']
del df2['pocet_umrti_komplikovany']
grouped2 = df2.groupby('vek_kat')
res = grouped2.sum()
res['procento'] = res['pocet_zemreli'] / res['pocet_pozitivni'] * 100
res.loc['65+']

pocet_pozitivni    49711.0000
pocet_zemreli       3380.0000
procento               6.7993
Name: 65+, dtype: float64