In [26]:
import pandas as pd
import glob, os

path = r'./COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/'
all_files = glob.glob(os.path.join(path, "*.csv"))

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

df = pd.concat(li, axis=0, ignore_index=True)

In [19]:
df.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Latitude,Longitude
0,Hubei,Mainland China,2020-02-26T14:13:10,65187.0,2615.0,20969.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Guangdong,Mainland China,2020-02-26T10:33:02,1347.0,7.0,851.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Henan,Mainland China,2020-02-26T10:33:02,1271.0,19.0,1033.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,South Korea,2020-02-26T11:03:11,1261.0,12.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Zhejiang,Mainland China,2020-02-26T10:33:02,1205.0,1.0,867.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.sort_values(by="Active", ascending=False).head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Latitude,Longitude
732106,NaN,NaN,NaN,766421.0,32714.0,83544.0,NaN,NaN,NaN,France,2020-10-14 04:24:05,46.2276,2.2137,649353.0,France,1172.895370,4.268411,NaN,NaN
728150,NaN,NaN,NaN,745104.0,32456.0,82402.0,NaN,NaN,NaN,France,2020-10-13 04:24:02,46.2276,2.2137,630099.0,France,1141.251600,4.355902,NaN,NaN
193986,NaN,NaN,NaN,702148.0,32356.0,81739.0,NaN,NaN,NaN,France,2020-10-12 04:23:45,46.2276,2.2137,588053.0,France,1075.701274,4.608145,NaN,NaN
197941,NaN,NaN,NaN,702148.0,32356.0,81739.0,NaN,NaN,NaN,France,2020-10-11 04:23:46,46.2276,2.2137,588053.0,France,1075.701274,4.608145,NaN,NaN
477610,NaN,NaN,NaN,702148.0,32356.0,81763.0,NaN,NaN,NaN,France,2020-10-10 04:23:57,46.2276,2.2137,588029.0,France,1075.701274,4.608145,NaN,NaN

In [30]:
df[df['Country_Region'] == 'Czechia'].sort_values(by='Confirmed', ascending=False)

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Latitude,Longitude
732078,NaN,NaN,NaN,129747.0,1106.0,59901.0,NaN,NaN,NaN,Czechia,2020-10-14 04:24:05,49.8175,15.473,68740.0,Czechia,1211.571744,0.852428,NaN,NaN
728122,NaN,NaN,NaN,121421.0,1051.0,58200.0,NaN,NaN,NaN,Czechia,2020-10-13 04:24:02,49.8175,15.473,62170.0,Czechia,1133.823925,0.865583,NaN,NaN
193958,NaN,NaN,NaN,117110.0,987.0,54980.0,NaN,NaN,NaN,Czechia,2020-10-12 04:23:45,49.8175,15.473,61143.0,Czechia,1093.567997,0.842797,NaN,NaN
197913,NaN,NaN,NaN,114005.0,948.0,54909.0,NaN,NaN,NaN,Czechia,2020-10-11 04:23:46,49.8175,15.473,58148.0,Czechia,1064.573645,0.831542,NaN,NaN
477582,NaN,NaN,NaN,109374.0,905.0,53173.0,NaN,NaN,NaN,Czechia,2020-10-10 04:23:57,49.8175,15.473,55296.0,Czechia,1021.329572,0.827436,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549118,NaN,NaN,NaN,1925.0,9.0,10.0,NaN,NaN,NaN,Czechia,2020-03-26 23:48:18,49.8175,15.473,1906.0,Czechia,NaN,NaN,NaN,NaN
32062,NaN,NaN,NaN,1654.0,6.0,10.0,NaN,NaN,NaN,Czechia,2020-03-25 23:33:04,49.8175,15.473,1638.0,Czechia,NaN,NaN,NaN,NaN
28646,NaN,NaN,NaN,1394.0,3.0,10.0,NaN,NaN,NaN,Czechia,2020-03-24 23:37:15,49.8175,15.473,1381.0,Czechia,NaN,NaN,NaN,NaN
312159,NaN,NaN,NaN,1236.0,1.0,7.0,NaN,NaN,NaN,Czechia,2020-03-23 23:19:21,49.8175,15.473,1228.0,Czechia,NaN,NaN,NaN,NaN
315533,NaN,NaN,NaN,1120.0,1.0,6.0,NaN,NaN,NaN,Czechia,3/22/20 23:45,49.8175,15.473,1113.0,Czechia,NaN,NaN,NaN,NaN