In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
df = pd.read_csv('modely_03_testy_pozitivnich_2020-10-27-16-38-26.csv', delimiter=';', encoding='iso-8859-1')
df2 = pd.read_csv('modely_01_okresni_statistika_2020-10-27-16-38-23.csv', delimiter=';', encoding='iso-8859-1')
df

,datum_vysledku,okres,orp,pohlavi,vek_kat,pocet_pozitivni_primarni,pocet_testu_u_pozitivnich,pocet_opakovanych
0,2020-03-03,CZ0100,Praha,Z,20-64,1.0,1.0,0.0
1,2020-03-03,CZ0724,Zlín,Z,65+,NaN,1.0,NaN
2,2020-03-07,CZ0723,Ronov pod Radhotìm,Z,20-64,1.0,NaN,NaN
3,2020-03-09,CZ0427,Ústí nad Labem,M,20-64,NaN,2.0,NaN
4,2020-03-09,CZ0524,Kostelec nad Orlicí,M,20-64,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...
87780,2020-10-27,CZ0803,Orlová,M,20-64,8.0,9.0,1.0
87781,2020-10-27,CZ0804,Kopøivnice,M,0-19,1.0,2.0,1.0
87782,2020-10-27,CZ0804,Nový Jièín,Z,20-64,2.0,4.0,2.0
87783,2020-10-27,CZ0805,Vítkov,Z,0-19,1.0,2.0,1.0
87784,2020-10-27,CZ0806,Ostrava,Z,65+,11.0,25.0,14.0

In [32]:
df2

,datum,okres,orp,pohlavi,vek_kat,pocet_pozitivni,pocet_vyleceni,pocet_zemreli,pocet_umrti_hospitalizace,pocet_umrti_komplikovany
0,2020-03-25,CZ0203,2024,M,65+,NaN,NaN,1.0,0.0,0.0
1,2020-03-29,CZ0100,0,Z,65+,2.0,NaN,2.0,2.0,1.0
2,2020-03-29,CZ0532,5309,Z,65+,NaN,NaN,1.0,1.0,1.0
3,2020-04-09,CZ0209,2003,M,65+,NaN,NaN,1.0,1.0,1.0
4,2020-04-11,CZ0100,0,M,65+,1.0,4.0,2.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
66379,2020-10-27,CZ0803,9999,Z,0-19,4.0,NaN,NaN,NaN,NaN
66380,2020-10-27,CZ0804,8001,Z,0-19,1.0,NaN,NaN,NaN,NaN
66381,2020-10-27,CZ0804,8012,M,65+,1.0,NaN,NaN,NaN,NaN
66382,2020-10-27,CZ0805,8013,Z,65+,1.0,NaN,NaN,NaN,NaN
66383,2020-10-27,CZ0805,9999,M,0-19,3.0,NaN,NaN,NaN,NaN

In [33]:
grouped = df.groupby('vek_kat')
grouped.sum()

,pocet_pozitivni_primarni,pocet_testu_u_pozitivnich,pocet_opakovanych
vek_kat,,,
0-19,36627.0,88270.0,41113.0
20-64,202934.0,527670.0,274510.0
65+,37573.0,106856.0,48938.0

In [34]:
grouped2 = df2.groupby('vek_kat')
grouped2.sum()

,orp,pocet_pozitivni,pocet_vyleceni,pocet_zemreli,pocet_umrti_hospitalizace,pocet_umrti_komplikovany
vek_kat,,,,,,
0-19,83961822,36627.0,17414.0,0.0,0.0,0.0
20-64,184110899,202934.0,74917.0,199.0,165.0,129.0
65+,84198780,37573.0,11839.0,2318.0,2009.0,1336.0